/**
 * Grupo-pai (categoria mestre real do TikTok Shop) por folha do CATALOG.
 *
 * O `Product.categoryUrl` guardado é sempre um segmento único (ex.:
 * `/c/costume-jewelry-accessories/905608`) — o CATALOG nunca armazenou a
 * hierarquia completa do TikTok, só a folha coletada. Por isso
 * `parseCategory()`, ao ver um único slug na URL, não tinha como saber a
 * categoria mestre e caía no rótulo genérico "TikTok Shop" para 100% dos
 * produtos — confirmado ao vivo em 2026-08-20 (top 30 do /analytics/product-score
 * todos "TikTok Shop", coluna "categoria" do ranking inútil na prática).
 *
 * Gerado a partir dos comentários de grupo em scripts/scrape-all-categories.mjs
 * (os mesmos 28 grupos do sitemap oficial TikTok Shop BR) — não é uma
 * classificação inventada, é a organização que o próprio CATALOG já usa.
 * Regerar com o mesmo parser se o CATALOG ganhar categorias novas fora dos
 * 28 grupos existentes.
 */
export const CATEGORY_GROUP_BY_SLUG_ID = {
  "women-s-underwear/842888": "Roupas femininas e roupas íntimas femininas",
  "women-s-suits-sets/842760": "Roupas femininas e roupas íntimas femininas",
  "women-s-dresses/842504": "Roupas femininas e roupas íntimas femininas",
  "women-s-tops/842248": "Roupas femininas e roupas íntimas femininas",
  "women-s-sleepwear-loungewear/843016": "Roupas femininas e roupas íntimas femininas",
  "women-s-bottoms/842376": "Roupas femininas e roupas íntimas femininas",
  "women-s-special-clothing/842632": "Roupas femininas e roupas íntimas femininas",
  "mobile-phone-accessories/909064": "Telefones e eletrônicos",
  "audio-video/909320": "Telefones e eletrônicos",
  "smart-wearable-devices/909576": "Telefones e eletrônicos",
  "cameras-photography/909192": "Telefones e eletrônicos",
  "universal-accessories/978952": "Telefones e eletrônicos",
  "gaming-consoles/909448": "Telefones e eletrônicos",
  "phones-tablets/995976": "Telefones e eletrônicos",
  "tablet-computer-accessories/984584": "Telefones e eletrônicos",
  "refurbished-electronics/2109072": "Telefones e eletrônicos",
  "education-devices/909704": "Telefones e eletrônicos",
  "smart-wearable-devices/2108944": "Telefones e eletrônicos",
  "eyewear/905352": "Acessórios de moda",
  "hair-accessories/905864": "Acessórios de moda",
  "costume-jewelry-accessories/905608": "Acessórios de moda",
  "hair-extensions-wigs/810128": "Acessórios de moda",
  "clothes-accessories/905224": "Acessórios de moda",
  "fashion-watches-accessories/905480": "Acessórios de moda",
  "dressmaking-fabrics/843144": "Acessórios de moda",
  "wedding-accessories/888592": "Acessórios de moda",
  "men-s-tops/839944": "Roupas masculinas e roupas íntimas masculinas",
  "men-s-bottoms/840072": "Roupas masculinas e roupas íntimas masculinas",
  "men-s-suits-sets/840712": "Roupas masculinas e roupas íntimas masculinas",
  "men-s-underwear-socks/840456": "Roupas masculinas e roupas íntimas masculinas",
  "men-s-sleepwear-loungewear/840584": "Roupas masculinas e roupas íntimas masculinas",
  "men-s-special-occasion-clothing/840328": "Roupas masculinas e roupas íntimas masculinas",
  "home-care-supplies/852232": "Suprimentos domésticos",
  "bathroom-supplies/851976": "Suprimentos domésticos",
  "home-organizers/851848": "Suprimentos domésticos",
  "home-decor/852104": "Suprimentos domésticos",
  "festive-party-supplies/852488": "Suprimentos domésticos",
  "laundry-tools-accessories/852360": "Suprimentos domésticos",
  "miscellaneous-home/852616": "Suprimentos domésticos",
  "hand-foot-care/849032": "Beleza e cuidados pessoais",
  "eye-ear-care/849544": "Beleza e cuidados pessoais",
  "personal-care-appliances/849416": "Beleza e cuidados pessoais",
  "makeup/848648": "Beleza e cuidados pessoais",
  "skincare/848776": "Beleza e cuidados pessoais",
  "haircare-styling/848904": "Beleza e cuidados pessoais",
  "nasal-oral-care/849672": "Beleza e cuidados pessoais",
  "bath-body-care/849160": "Beleza e cuidados pessoais",
  "fragrance/856208": "Beleza e cuidados pessoais",
  "special-personal-care/981128": "Beleza e cuidados pessoais",
  "men-s-care/849288": "Beleza e cuidados pessoais",
  "feminine-care/849800": "Beleza e cuidados pessoais",
  "shoe-accessories/900744": "Sapatos",
  "women-s-shoes/900488": "Sapatos",
  "men-s-shoes/900616": "Sapatos",
  "sports-outdoor-accessories/834824": "Esportes e atividades ao ar livre",
  "sport-outdoor-clothing/834568": "Esportes e atividades ao ar livre",
  "fitness/835336": "Esportes e atividades ao ar livre",
  "swimwear-surfwear-wetsuits/846224": "Esportes e atividades ao ar livre",
  "sports-footwear/834696": "Esportes e atividades ao ar livre",
  "camping-hiking/835464": "Esportes e atividades ao ar livre",
  "ball-sports/834952": "Esportes e atividades ao ar livre",
  "water-sports/835080": "Esportes e atividades ao ar livre",
  "leisure-outdoor-recreation-equipment/835592": "Esportes e atividades ao ar livre",
  "winter-sports/835208": "Esportes e atividades ao ar livre",
  "fan-shop/936712": "Esportes e atividades ao ar livre",
  "lawn-games/2108816": "Esportes e atividades ao ar livre",
  "women-s-bags/902408": "Malas e bolsas",
  "men-s-bags/902536": "Malas e bolsas",
  "functional-bags/902792": "Malas e bolsas",
  "luggage-travel-bags/902664": "Malas e bolsas",
  "bag-accessories/902920": "Malas e bolsas",
  "classic-novelty-toys/860296": "Brinquedos e passatempos",
  "dolls-stuffed-toys/859656": "Brinquedos e passatempos",
  "games-puzzles/860168": "Brinquedos e passatempos",
  "sports-outdoor-play/859912": "Brinquedos e passatempos",
  "educational-toys/859784": "Brinquedos e passatempos",
  "diy/951560": "Brinquedos e passatempos",
  "electric-remote-control-toys/860040": "Brinquedos e passatempos",
  "musical-instruments-accessories/860552": "Brinquedos e passatempos",
  "car-interior-accessories/930184": "Automotivo e moto",
  "car-washing-maintenance/940808": "Automotivo e moto",
  "car-repair-tools/940296": "Automotivo e moto",
  "car-electronics/929928": "Automotivo e moto",
  "car-lights/940424": "Automotivo e moto",
  "car-exterior-accessories/930056": "Automotivo e moto",
  "motorcycle-accessories/940936": "Automotivo e moto",
  "quads-motorhomes-boats/940680": "Automotivo e moto",
  "auto-replacement-parts/809488": "Automotivo e moto",
  "motorcycle-parts/809616": "Automotivo e moto",
  "girls-footwear/806024": "Moda para crianças",
  "boys-clothes/802312": "Moda para crianças",
  "girls-clothes/803592": "Moda para crianças",
  "kids-fashion-accessories/806792": "Moda para crianças",
  "boys-footwear/805128": "Moda para crianças",
  "drinkware/859400": "Utensílios de cozinha",
  "kitchen-utensils-gadgets/859528": "Utensílios de cozinha",
  "bakeware/859016": "Utensílios de cozinha",
  "kitchen-knives/858632": "Utensílios de cozinha",
  "cookware/859144": "Utensílios de cozinha",
  "bar-wine-utensils/858888": "Utensílios de cozinha",
  "cutlery-tableware/859272": "Utensílios de cozinha",
  "barbecue/858760": "Utensílios de cozinha",
  "tea-coffeeware/858504": "Utensílios de cozinha",
  "office-stationery-supplies/831112": "Computadores e equipamentos de escritório",
  "data-storage-software/828168": "Computadores e equipamentos de escritório",
  "computer-accessories/826760": "Computadores e equipamentos de escritório",
  "office-equipment/830344": "Computadores e equipamentos de escritório",
  "desktop-laptop-components/825352": "Computadores e equipamentos de escritório",
  "network-components/829192": "Computadores e equipamentos de escritório",
  "desktop-computers-laptops-tablets/824840": "Computadores e equipamentos de escritório",
  "baby-care-health/879112": "Bebê e maternidade",
  "baby-clothing-shoes/877320": "Bebê e maternidade",
  "baby-furniture/878216": "Bebê e maternidade",
  "maternity-supplies/880008": "Bebê e maternidade",
  "baby-toys/878984": "Bebê e maternidade",
  "baby-safety/878600": "Bebê e maternidade",
  "baby-travel-gear/877576": "Bebê e maternidade",
  "baby-fashion-accessories/961928": "Bebê e maternidade",
  "nursing-feeding/877832": "Bebê e maternidade",
  "measuring-tools/871816": "Ferramentas e hardware",
  "power-tools/871560": "Ferramentas e hardware",
  "garden-tools/871944": "Ferramentas e hardware",
  "hardware/872328": "Ferramentas e hardware",
  "soldering-equipment/872072": "Ferramentas e hardware",
  "hand-tools/871688": "Ferramentas e hardware",
  "pumps-plumbing/980488": "Ferramentas e hardware",
  "tool-organizers/872200": "Ferramentas e hardware",
  "bedding-and-linens/808328": "Têxteis e móveis",
  "household-textiles/809992": "Têxteis e móveis",
  "fabrics-sewing-supplies/811016": "Têxteis e móveis",
  "dog-cat-grooming/816392": "Suprimentos para animais de estimação",
  "dog-cat-litter/815624": "Suprimentos para animais de estimação",
  "dog-cat-accessories/818696": "Suprimentos para animais de estimação",
  "fish-aquatic-supplies/819848": "Suprimentos para animais de estimação",
  "dog-cat-healthcare/818184": "Suprimentos para animais de estimação",
  "small-animal-supplies/822792": "Suprimentos para animais de estimação",
  "dog-cat-clothing/813960": "Suprimentos para animais de estimação",
  "dog-cat-food/812168": "Suprimentos para animais de estimação",
  "farm-animal-poultry-supplies/1001992": "Suprimentos para animais de estimação",
  "dog-cat-furniture/812808": "Suprimentos para animais de estimação",
  "bird-supplies/821896": "Suprimentos para animais de estimação",
  "reptile-amphibian-supplies/821000": "Suprimentos para animais de estimação",
  "bathroom-fixtures/873096": "Reformas residenciais",
  "garden-supplies/873352": "Reformas residenciais",
  "lights-lighting/872456": "Reformas residenciais",
  "building-supplies/872968": "Reformas residenciais",
  "kitchen-fixtures/872712": "Reformas residenciais",
  "electrical-equipment-supplies/872584": "Reformas residenciais",
  "security-safety/873224": "Reformas residenciais",
  "smart-home-systems/872840": "Reformas residenciais",
  "solar-wind-power/808208": "Reformas residenciais",
  "pantry-food/914952": "Alimentos e bebidas",
  "drinks/914824": "Alimentos e bebidas",
  "snacks/915336": "Alimentos e bebidas",
  "staples-cooking-essentials/915080": "Alimentos e bebidas",
  "baking/915208": "Alimentos e bebidas",
  "milk-dairy/809744": "Alimentos e bebidas",
  "fresh-frozen-food/915464": "Alimentos e bebidas",
  "beer-wine-spirits/914696": "Alimentos e bebidas",
  "hijabs/601304": "Moda muçulmana",
  "women-s-islamic-clothing/601310": "Moda muçulmana",
  "men-s-islamic-clothing/601325": "Moda muçulmana",
  "islamic-accessories/601343": "Moda muçulmana",
  "prayer-attire-equipment/601348": "Moda muçulmana",
  "islamic-sportswear/838920": "Moda muçulmana",
  "outerwear/601331": "Moda muçulmana",
  "kids-islamic-clothing/601339": "Moda muçulmana",
  "umroh-equipment/839176": "Moda muçulmana",
  "humanities-social-sciences/927112": "Livros, revistas e áudios",
  "lifestyle-hobbies/992392": "Livros, revistas e áudios",
  "literature-art/986760": "Livros, revistas e áudios",
  "education-schooling/992904": "Livros, revistas e áudios",
  "children-s-infants-books/989704": "Livros, revistas e áudios",
  "economics-management/989320": "Livros, revistas e áudios",
  "science-technology/990216": "Livros, revistas e áudios",
  "magazines-newspapers/985736": "Livros, revistas e áudios",
  "video-music/997384": "Livros, revistas e áudios",
  "home-appliances/844808": "Eletrodomésticos",
  "kitchen-appliances/844168": "Eletrodomésticos",
  "large-home-appliances/845064": "Eletrodomésticos",
  "commercial-appliances/845320": "Eletrodomésticos",
  "nutrition-wellness/700646": "Saúde",
  "alternative-medications-treatments/950792": "Saúde",
  "medical-supplies/924424": "Saúde",
  "commercial-furniture/871432": "Móveis",
  "outdoor-furniture/871176": "Móveis",
  "indoor-furniture/871048": "Móveis",
  "children-s-furniture/871304": "Móveis",
  "home-furniture/604454": "Móveis",
  "natural-crystal/955400": "Joias, acessórios e derivados",
  "artificial-gemstones/964360": "Joias, acessórios e derivados",
  "platinum-carat-gold/954888": "Joias, acessórios e derivados",
  "silver/955144": "Joias, acessórios e derivados",
  "non-natural-crystal/961800": "Joias, acessórios e derivados",
  "jade/963848": "Joias, acessórios e derivados",
  "semiprecious-stones/964232": "Joias, acessórios e derivados",
  "pearl/964488": "Joias, acessórios e derivados",
  "mellite/964744": "Joias, acessórios e derivados",
  "amber/964616": "Joias, acessórios e derivados",
  "gold/955016": "Joias, acessórios e derivados",
  "diamond/955272": "Joias, acessórios e derivados",
  "ruby-sapphire-emerald/964104": "Joias, acessórios e derivados",
  "trading-cards-accessories/810000": "Colecionáveis",
  "sports-collectibles/937736": "Colecionáveis",
  "entertainment/953352": "Colecionáveis",
  "cultural-items/809872": "Colecionáveis",
  "footwear/857360": "Pre-Owned",
  "pre-loved-luggage-bags/857232": "Pre-Owned",
  "fashion-accessories/857104": "Pre-Owned",
  "luggage-travel/864656": "Pre-Owned",
  "collectible-trading-cards/856976": "Pre-Owned",
  "refurbished-phones-electronics/857744": "Pre-Owned"
};
